// <auto-generated />
namespace Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Unamas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Unamas));
        
        string IMigrationMetadata.Id
        {
            get { return "202505020221337_Unamas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
